<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"用户表管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户表管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"保险管理",
                        "menuJump":"列表",
                        "tableName":"baoxian"
                    }
                ],
                "menu":"保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除",
                        ],
                        "menu":"保险类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"保险类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                        ],
                        "menu":"已有保险管理",
                        "menuJump":"列表",
                        "tableName":"gaoumai"
                    }
                ],
                "menu":"已有保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除",
                            "拒绝",
                            "同意",
                        ],
                        "menu":"赔偿申请管理",
                        "menuJump":"列表",
                        "tableName":"shenqing"
                    }
                ],
                "menu":"赔偿申请管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "购买",
                        ],
                        "menu":"保险管理",
                        "menuJump":"列表",
                        "tableName":"baoxian"
                    }
                ],
                "menu":"保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"保险类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionary"
                    }
                ],
                "menu":"保险类型管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "申请",
                        ],
                        "menu":"已有保险管理",
                        "menuJump":"列表",
                        "tableName":"gaoumai"
                    }
                ],
                "menu":"已有保险管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                        ],
                        "menu":"赔偿申请管理",
                        "menuJump":"列表",
                        "tableName":"shenqing"
                    }
                ],
                "menu":"赔偿申请管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"用户",
        "tableName":"yonghu"
    }
];

var hasMessage = '';
